import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { motion } from 'framer-motion';
import { FiFileText, FiDownload, FiPlus } from 'react-icons/fi';
import { getMyPrescriptions, getIssuedPrescriptions, reset } from '../../store/slices/prescriptionSlice';
import { useToast } from '../../context/ToastContext';
import WritePrescriptionModal from '../../components/dashboard/WritePrescriptionModal';
import jsPDF from 'jspdf';

const Prescriptions = () => {
  const dispatch = useDispatch();
  const { addToast } = useToast();
  const { user } = useSelector((state) => state.auth);
  const { prescriptions, isLoading, isError, message } = useSelector((state) => state.prescription);

  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    if (isError) {
      addToast(message, 'error');
    }

    if (user?.role === 'doctor') {
      dispatch(getIssuedPrescriptions());
    } else {
      dispatch(getMyPrescriptions());
    }

    return () => {
      dispatch(reset());
    };
  }, [dispatch, user?.role, isError, message, addToast]);

  const generatePDF = (prescription) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(33, 150, 243);
    doc.text('Smart_Doc Prescription', 105, 20, null, null, 'center');
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${new Date(prescription.createdAt).toLocaleDateString()}`, 20, 40);
    
    // Doctor Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text('Doctor Details:', 20, 60);
    doc.setFontSize(12);
    doc.text(`Name: Dr. ${prescription.doctorId?.userId?.name || 'N/A'}`, 20, 70);
    
    // Patient Info
    doc.setFontSize(14);
    doc.text('Patient Details:', 120, 60);
    doc.setFontSize(12);
    doc.text(`Name: ${prescription.patientId?.name || 'N/A'}`, 120, 70);

    // Diagnosis
    doc.setFontSize(14);
    doc.text('Diagnosis:', 20, 90);
    doc.setFontSize(12);
    doc.text(prescription.diagnosis, 20, 100);

    // Medications
    doc.setFontSize(14);
    doc.text('Medications:', 20, 120);
    doc.setFontSize(12);
    let yPos = 130;
    prescription.medications.forEach((med, index) => {
      doc.text(`${index + 1}. ${med.name} - ${med.dosage} (${med.frequency} for ${med.duration})`, 20, yPos);
      if (med.instructions) {
        doc.text(`   Instructions: ${med.instructions}`, 20, yPos + 7);
        yPos += 15;
      } else {
        yPos += 10;
      }
    });

    if (prescription.notes) {
      doc.setFontSize(14);
      doc.text('Additional Notes:', 20, yPos + 10);
      doc.setFontSize(12);
      doc.text(prescription.notes, 20, yPos + 20);
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Smart_Doc Platform', 105, 280, null, null, 'center');

    doc.save(`Prescription_${prescription._id}.pdf`);
    addToast('PDF downloaded successfully!', 'success');
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-gray-900">
          {user?.role === 'doctor' ? 'Issued Prescriptions' : 'My Prescriptions'}
        </h2>
        {user?.role === 'doctor' && (
          <button
            onClick={() => setIsModalOpen(true)}
            className="btn-primary flex items-center gap-2 py-2 px-4"
          >
            <FiPlus /> Write Prescription
          </button>
        )}
      </div>

      {isLoading ? (
        <div className="flex justify-center p-12">
          <div className="w-10 h-10 border-4 border-primary-200 border-t-primary-600 rounded-full animate-spin"></div>
        </div>
      ) : prescriptions.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {prescriptions.map((prescription, index) => (
            <motion.div
              key={prescription._id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
              className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 flex flex-col h-full hover:shadow-md transition-shadow"
            >
              <div className="flex justify-between items-start mb-4">
                <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-500 flex items-center justify-center text-xl">
                  <FiFileText />
                </div>
                <button
                  onClick={() => generatePDF(prescription)}
                  className="text-gray-400 hover:text-primary-600 transition-colors tooltip p-2"
                  title="Download PDF"
                >
                  <FiDownload size={20} />
                </button>
              </div>

              <div className="mb-4">
                <h3 className="text-lg font-bold text-gray-900 truncate" title={prescription.diagnosis}>
                  {prescription.diagnosis}
                </h3>
                <p className="text-sm text-gray-500">
                  {new Date(prescription.createdAt).toLocaleDateString()}
                </p>
              </div>

              <div className="flex-1 space-y-3">
                <div className="text-sm">
                  <span className="text-gray-500">
                    {user?.role === 'doctor' ? 'Patient: ' : 'Doctor: '}
                  </span>
                  <span className="font-semibold text-gray-900">
                    {user?.role === 'doctor' 
                      ? prescription.patientId?.name 
                      : `Dr. ${prescription.doctorId?.userId?.name}`}
                  </span>
                </div>
                
                <div className="text-sm">
                  <span className="text-gray-500">Medications: </span>
                  <span className="font-semibold text-gray-900">{prescription.medications?.length || 0}</span>
                </div>

                <div className="mt-4 p-3 bg-gray-50 rounded-xl max-h-32 overflow-y-auto custom-scrollbar text-xs">
                  {prescription.medications?.map((med, i) => (
                    <div key={i} className="mb-2 last:mb-0 border-b border-gray-200 last:border-0 pb-2 last:pb-0">
                      <p className="font-bold text-primary-700">{med.name}</p>
                      <p className="text-gray-600">{med.dosage} - {med.frequency}</p>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      ) : (
        <div className="text-center py-16 bg-white rounded-2xl border border-gray-100">
          <FiFileText className="mx-auto text-5xl text-gray-300 mb-4" />
          <p className="text-gray-500 font-medium text-lg">No prescriptions found.</p>
        </div>
      )}

      {isModalOpen && <WritePrescriptionModal onClose={() => setIsModalOpen(false)} />}
    </div>
  );
};

export default Prescriptions;
